name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          VERCEL: ${{ secrets.VERCEL }}
        run: |
          python manage.py migrate

      - name: Load fixture data
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          VERCEL: ${{ secrets.VERCEL }}
        run: |
          python manage.py loaddata fixtures/initial_data.json

      - name: Collect static files
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          VERCEL: ${{ secrets.VERCEL }}
        run: python manage.py collectstatic --noinput

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          VERCEL: ${{ secrets.VERCEL }}
        run: |
          npm install -g vercel
          vercel --token $VERCEL_TOKEN --prod --confirm
